// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import Forms__CourseTypeUnitController from "./forms/course_type_unit_controller"
application.register("forms--course-type-unit", Forms__CourseTypeUnitController)

import Forms__PersonController from "./forms/person_controller"
application.register("forms--person", Forms__PersonController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TselectController from "./tselect_controller"
application.register("tselect", TselectController)
