// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import Forms__AnswerController from "./forms/answer_controller"
application.register("forms--answer", Forms__AnswerController)

import Forms__CertificatesController from "./forms/certificates_controller"
application.register("forms--certificates", Forms__CertificatesController)

import Forms__CourseClientController from "./forms/course_client_controller"
application.register("forms--course-client", Forms__CourseClientController)

import Forms__CourseController from "./forms/course_controller"
application.register("forms--course", Forms__CourseController)

import Forms__CourseHoursTurnController from "./forms/course_hours_turn_controller"
application.register("forms--course-hours-turn", Forms__CourseHoursTurnController)

import Forms__CoursePersonController from "./forms/course_person_controller"
application.register("forms--course-person", Forms__CoursePersonController)

import Forms__CourseTypeUnitController from "./forms/course_type_unit_controller"
application.register("forms--course-type-unit", Forms__CourseTypeUnitController)

import Forms__InvoiceController from "./forms/invoice_controller"
application.register("forms--invoice", Forms__InvoiceController)

import Forms__PersonController from "./forms/person_controller"
application.register("forms--person", Forms__PersonController)

import Forms__PriceCourseController from "./forms/price_course_controller"
application.register("forms--price-course", Forms__PriceCourseController)

import Forms__RegisterAttendanceController from "./forms/register_attendance_controller"
application.register("forms--register-attendance", Forms__RegisterAttendanceController)

import Forms__RegisterScoringController from "./forms/register_scoring_controller"
application.register("forms--register-scoring", Forms__RegisterScoringController)

import Forms__RegisterToCourseController from "./forms/register_to_course_controller"
application.register("forms--register-to-course", Forms__RegisterToCourseController)

import Forms__TurnController from "./forms/turn_controller"
application.register("forms--turn", Forms__TurnController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TselectController from "./tselect_controller"
application.register("tselect", TselectController)
