require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/course_people", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CoursePerson. As you add validations to CoursePerson, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CoursePerson.create! valid_attributes
      get course_people_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      course_person = CoursePerson.create! valid_attributes
      get course_person_url(course_person)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_course_person_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      course_person = CoursePerson.create! valid_attributes
      get edit_course_person_url(course_person)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CoursePerson" do
        expect {
          post course_people_url, params: { course_person: valid_attributes }
        }.to change(CoursePerson, :count).by(1)
      end

      it "redirects to the created course_person" do
        post course_people_url, params: { course_person: valid_attributes }
        expect(response).to redirect_to(course_person_url(CoursePerson.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CoursePerson" do
        expect {
          post course_people_url, params: { course_person: invalid_attributes }
        }.to change(CoursePerson, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post course_people_url, params: { course_person: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested course_person" do
        course_person = CoursePerson.create! valid_attributes
        patch course_person_url(course_person), params: { course_person: new_attributes }
        course_person.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the course_person" do
        course_person = CoursePerson.create! valid_attributes
        patch course_person_url(course_person), params: { course_person: new_attributes }
        course_person.reload
        expect(response).to redirect_to(course_person_url(course_person))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        course_person = CoursePerson.create! valid_attributes
        patch course_person_url(course_person), params: { course_person: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested course_person" do
      course_person = CoursePerson.create! valid_attributes
      expect {
        delete course_person_url(course_person)
      }.to change(CoursePerson, :count).by(-1)
    end

    it "redirects to the course_people list" do
      course_person = CoursePerson.create! valid_attributes
      delete course_person_url(course_person)
      expect(response).to redirect_to(course_people_url)
    end
  end
end
