require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/exam_modules", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ExamModule. As you add validations to ExamModule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ExamModule.create! valid_attributes
      get exam_modules_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      exam_module = ExamModule.create! valid_attributes
      get exam_module_url(exam_module)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_exam_module_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      exam_module = ExamModule.create! valid_attributes
      get edit_exam_module_url(exam_module)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ExamModule" do
        expect {
          post exam_modules_url, params: { exam_module: valid_attributes }
        }.to change(ExamModule, :count).by(1)
      end

      it "redirects to the created exam_module" do
        post exam_modules_url, params: { exam_module: valid_attributes }
        expect(response).to redirect_to(exam_module_url(ExamModule.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ExamModule" do
        expect {
          post exam_modules_url, params: { exam_module: invalid_attributes }
        }.to change(ExamModule, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post exam_modules_url, params: { exam_module: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested exam_module" do
        exam_module = ExamModule.create! valid_attributes
        patch exam_module_url(exam_module), params: { exam_module: new_attributes }
        exam_module.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the exam_module" do
        exam_module = ExamModule.create! valid_attributes
        patch exam_module_url(exam_module), params: { exam_module: new_attributes }
        exam_module.reload
        expect(response).to redirect_to(exam_module_url(exam_module))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        exam_module = ExamModule.create! valid_attributes
        patch exam_module_url(exam_module), params: { exam_module: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested exam_module" do
      exam_module = ExamModule.create! valid_attributes
      expect {
        delete exam_module_url(exam_module)
      }.to change(ExamModule, :count).by(-1)
    end

    it "redirects to the exam_modules list" do
      exam_module = ExamModule.create! valid_attributes
      delete exam_module_url(exam_module)
      expect(response).to redirect_to(exam_modules_url)
    end
  end
end
