require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/prices", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Price. As you add validations to Price, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Price.create! valid_attributes
      get prices_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      price = Price.create! valid_attributes
      get price_url(price)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_price_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      price = Price.create! valid_attributes
      get edit_price_url(price)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Price" do
        expect {
          post prices_url, params: { price: valid_attributes }
        }.to change(Price, :count).by(1)
      end

      it "redirects to the created price" do
        post prices_url, params: { price: valid_attributes }
        expect(response).to redirect_to(price_url(Price.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Price" do
        expect {
          post prices_url, params: { price: invalid_attributes }
        }.to change(Price, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post prices_url, params: { price: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested price" do
        price = Price.create! valid_attributes
        patch price_url(price), params: { price: new_attributes }
        price.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the price" do
        price = Price.create! valid_attributes
        patch price_url(price), params: { price: new_attributes }
        price.reload
        expect(response).to redirect_to(price_url(price))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        price = Price.create! valid_attributes
        patch price_url(price), params: { price: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested price" do
      price = Price.create! valid_attributes
      expect {
        delete price_url(price)
      }.to change(Price, :count).by(-1)
    end

    it "redirects to the prices list" do
      price = Price.create! valid_attributes
      delete price_url(price)
      expect(response).to redirect_to(prices_url)
    end
  end
end
